version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  versioning-strategy: increase-if-necessary
  allow:
    - dependency-type: "all"
  schedule:
    interval: weekly
  groups:
    all-deps:
      patterns:
        - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
