# Helper script executed from CI to execute `wit-bindgen` and regenerate the
# bindings for the WASIp2 and WASIp3 targets.

set -ex

# Disable some features required for compat with really old toolchains/WASI
# versions that aren't required here.
args="--disable-custom-section-link-helpers"
args="$args --disable-run-ctors-once-workaround"

# Make the generated code a bit easier to read
args="$args --format"

# Use `feature = "std"` if needed, mostly intended for future compat if ever
# since this isn't needed currently.
args="$args --std-feature"

# Fail to compile if a runtime-path is actually needed, and it shouldn't be
# given the current generated bindings.
args="$args --runtime-path nonexisten"

# The custom section generated by wit-bindgen needs a globally unique version in
# the entire crate graph, so "salt" it with the `rand` crate's version which
# should be sufficient enough for now.
rand_version=$(cat Cargo.toml | grep '^version' | sed 's/version = "\(.*\)"/\1/')
args="$args --type-section-suffix rust-rand-${rand_version}"

# Skip generated bindings for functions that this crate doesn't use.
args="$args --skip=get-random-bytes"
args="$args --skip=get-insecure-random-bytes"
args="$args --skip=get-insecure-random-u64"
args="$args --skip=get-insecure-seed"

# WASIp2 bindings
wasip2=0.2.10
curl -LO https://github.com/WebAssembly/WASI/releases/download/v$wasip2/wasi-wit-$wasip2.tar.gz
tar xf wasi-wit-$wasip2.tar.gz
wit-bindgen rust $args ./wasi-wit-$wasip2/random \
  --world imports \
  --out-dir src/backends/wasi_p2_3/p2

# WASIp3 bindings
#
# Note that the folder structure is a bit different for WASIp2 for now, but it's
# expected to converge on the same structure as WASIp2 above eventually.
wasip3=0.3.0-rc-2026-01-06
curl -LO https://github.com/WebAssembly/WASI/archive/refs/tags/v$wasip3.tar.gz
tar xf v$wasip3.tar.gz
wit-bindgen rust $args ./WASI-$wasip3/proposals/random/wit-0.3.0-draft \
  --world imports \
  --out-dir src/backends/wasi_p2_3/p3
