name: Update Cargo.lock

on:
  # Allow manually running the update
  workflow_dispatch:
  # Run every Sunday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 0'

# We need permissions to commit code and open a pull request
permissions:
  contents: write
  pull-requests: write

jobs:
  update-cargo-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Update dependencies
        run: cargo update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Update Cargo.lock"
          commit-message: "Update Cargo.lock"
          base: master
          branch: update-cargo-lock
